
DROP DATABASE jee;

CREATE DATABASE jee DEFAULT CHARACTER SET UTF8;

GRANT ALL PRIVILEGES ON jee.* to jee@'%' IDENTIFIED BY 'jee';
GRANT ALL PRIVILEGES ON jee.* to jee@'localhost' IDENTIFIED BY 'jee';

